name: Build Wheels for New Release with Prioritization

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.14'
        default: 'v0.2.14'
        required: true
        type: string

permissions:
  contents: write

jobs:          
  build_textgen_wheels_prio:
    name: Textgen Prioritized
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      config: 'pyver:3.10;cuda:12.1.1'
      
  build_wheels_main_prio:
    name: Main Prioritized
    uses: ./.github/workflows/build-wheels.yml
    with:
      version: ${{ inputs.version }}
      cpu: '0'
      config: 'pyver:3.10;cuda:12.1.1'
      
  build_wheels_cpu_prio:
    name: CPU-only Prioritized
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      config: 'pyver:3.10;avx:basic'
      
  build_wheels_rocm_prio:
    name: ROCm Prioritized
    uses: ./.github/workflows/build-wheels-rocm-full.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:ubuntu-20.04;pyver:3.10;rocm:5.6.1;rename:1'
      exclude: 'None'
      
  build_wheels_macos_prio:
    name: MacOS Metal Prioritized
    uses: ./.github/workflows/build-wheels-macos.yml
    with:
      version: ${{ inputs.version }}
      config: 'pyver:3.10'
      
  build_wheels_main:
    name: Main Wheels
    needs: ['build_wheels_main_prio', 'build_textgen_wheels_prio', 'build_wheels_cpu_prio', 'build_wheels_rocm_prio', 'build_wheels_macos_prio']
    uses: ./.github/workflows/build-wheels.yml
    with:
      version: ${{ inputs.version }}
      cpu: '0'
      exclude: 'pyver:3.10,cuda:12.1.1'
      
  build_textgen_wheels:
    name: Textgen Wheels
    needs: build_wheels_main
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      exclude: 'pyver:3.10,cuda:12.1.1'

  build_textgen_tensorcores:
    name: Tensor Core CUDA wheels
    needs: build_wheels_main
    uses: ./.github/workflows/build-wheels-tensorcores.yml
    with:
      version: ${{ inputs.version }}
      
  build_wheels_cpu:
    name: CPU-only Wheels
    needs: build_textgen_tensorcores
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      exclude: 'pyver:3.10,avx:basic'
      
  build_wheels_macos:
    name: MacOS Metal Wheels
    needs: build_wheels_cpu
    uses: ./.github/workflows/build-wheels-macos.yml
    with:
      version: ${{ inputs.version }}
      exclude: 'pyver:3.10'
      
  build_wheels_rocm:
    name: ROCm Wheels
    needs: build_wheels_macos
    uses: ./.github/workflows/build-wheels-rocm-full.yml
    with:
      version: ${{ inputs.version }}
      exclude: 'os:ubuntu-20.04,pyver:3.10,rocm:5.6.1,rename:1'
