name: Build ROCm Wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_wheels_rocm:
    name: ROCm Wheels
    uses: ./.github/workflows/build-wheels-rocm-full.yml
    with:
      version: ${{ inputs.version }}
      config: 'rename:0'
