name: Build ROCm Windows Wheel

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.1.79'
        default: 'v0.1.79'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.1.79'
        default: 'v0.1.79'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build_libs:
    name: Build ROCm Lib
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: ${{ inputs.version }}
          submodules: 'recursive'
          
      - name: Install ROCm SDK
        run: |
          curl -LO https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe
          Start-Process 'AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe' -ArgumentList '-install' -NoNewWindow -Wait
          echo "C:\Program Files\AMD\ROCm\5.5\bin" >> $env:GITHUB_PATH
          echo 'ROCM_PATH=C:\Program Files\AMD\ROCm\5.5' >> $env:GITHUB_ENV
          echo 'HIP_PATH=C:\Program Files\AMD\ROCm\5.5' >> $env:GITHUB_ENV
          echo "ROCM_VERSION=5.5.1" >> $env:GITHUB_ENV
          
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Install Dependencies
        run: |
          python -m pip install cmake ninja
        
      - name: Build Lib
        run: |
          $env:CC = 'C:\Program Files\AMD\ROCm\5.5\bin\clang.exe'
          $env:CXX = 'C:\Program Files\AMD\ROCm\5.5\bin\clang++.exe'
          $env:CMAKE_PREFIX_PATH = 'C:\Program Files\AMD\ROCm\5.5'
          $env:VERBOSE = '1'
          $env:GPU_TARGETS = 'all'
          mkdir 'build'
          Set-Location '.\vendor\llama.cpp'
          cmake -B build -G "Ninja" -DLLAMA_HIPBLAS=ON -DBUILD_SHARED_LIBS=ON
          cmake --build build --config Release --target llama
          Copy-Item '.\build\bin\llama.dll' '..\..\build'
        
      - uses: actions/upload-artifact@v3
        with:
          name: 'win-rocm-lib'
          path: ./build/llama.dll
          
  build_wheel:
    name: Build ROCm Wheels
    runs-on: windows-latest
    needs: build_libs
    strategy:
      matrix:
        pyver: ["3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        shell: pwsh
    env:
      PCKGVER: ${{ inputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: ${{ inputs.version }}
          
      - uses: actions/download-artifact@v3
        with:
          name: 'win-rocm-lib'
          path: ./llama_cpp
          
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.pyver }}
          
      - name: Install Dependencies
        run: |
          python -m pip install build wheel cmake scikit-build ninja
        
      - name: Build Wheel
        run: |
          $packageVersion = [version]$env:PCKGVER.TrimStart('v')
          $setup = Get-Content 'setup.py' -raw
          if ($packageVersion -lt [version]'0.1.78') {$newsetup = $setup.Replace("packages=[`"llama_cpp`", `"llama_cpp.server`"],","packages=[`"llama_cpp`", `"llama_cpp.server`"],`n    package_data={'llama_cpp': ['llama.dll']},")}
          if ($packageVersion -gt [version]'0.1.77') {$newsetup = $setup.Replace('package_data={"llama_cpp": ["py.typed"]},','package_data={"llama_cpp": ["py.typed", "llama.dll"]},')}
          New-Item 'setup.py' -itemType File -value $newsetup -force
          python setup.py --skip-cmake bdist_wheel egg_info --tag-build=+rocm5.5.1
          
      - name: Upload files to a GitHub release
        id: upload-release
        uses: svenstaro/upload-release-action@2.6.1
        continue-on-error: true
        with:
          file: ./dist/*.whl
          tag: rocm
          file_glob: true
          make_latest: false
          overwrite: true
        
      - uses: actions/upload-artifact@v3
        if: steps.upload-release.outcome == 'failure'
        with:
          name: 'win-rocm-wheels'
          path: ./dist/*.whl
