name: Build Basic Wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_wheels_main:
    name: Main Wheels
    uses: ./.github/workflows/build-wheels.yml
    with:
      version: ${{ inputs.version }}
      cpu: '0'
      config: 'releasetag:basic'
