name: Build Basic Wheels for Text Generation Webui

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.9'
        default: 'v0.2.9'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_textgen_wheels:
    name: Textgen Wheels
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      config: 'avxver:basic'